"set guioptions=aegimrLt
set guioptions=aegit "sin menus
"set gfn=Input\ 13.5
set gfn=Input\ 11
"set gfn=PragmataPro\ For\ Powerline\ 12
"set gfn=DejaVu\ Sans\ Mono\ 11
"set linespace=2
set linespace=0
set co=95
set lines=999
