"set guioptions=aegimrLt
set guioptions=aegit "sin menus
set gfn=Consolas\ 13
"set gfn=M+\ 2m\ Medium\ 12
"set gfn=Input\ 11
"set gfn=PragmataPro\ For\ Powerline\ 12
set linespace=2
set co=100
set lines=999
